691166 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
116355 + 0 mapped (16.83%:-nan%)
691166 + 0 paired in sequencing
345583 + 0 read1
345583 + 0 read2
84318 + 0 properly paired (12.20%:-nan%)
108188 + 0 with itself and mate mapped
8167 + 0 singletons (1.18%:-nan%)
6 + 0 with mate mapped to a different chr
5 + 0 with mate mapped to a different chr (mapQ>=5)
