1048274 + 0 in total (QC-passed reads + QC-failed reads)
357108 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
528176 + 0 mapped (50.39%:-nan%)
691166 + 0 paired in sequencing
345583 + 0 read1
345583 + 0 read2
142734 + 0 properly paired (20.65%:-nan%)
160480 + 0 with itself and mate mapped
10588 + 0 singletons (1.53%:-nan%)
20 + 0 with mate mapped to a different chr
15 + 0 with mate mapped to a different chr (mapQ>=5)
