848494 + 0 in total (QC-passed reads + QC-failed reads)
157328 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
276910 + 0 mapped (32.64%:-nan%)
691166 + 0 paired in sequencing
345583 + 0 read1
345583 + 0 read2
87396 + 0 properly paired (12.64%:-nan%)
110874 + 0 with itself and mate mapped
8708 + 0 singletons (1.26%:-nan%)
6 + 0 with mate mapped to a different chr
5 + 0 with mate mapped to a different chr (mapQ>=5)
